// alert("HI");
// console.log(window); 
let heading1 = document.getElementsByClassName("heading");
console.log(heading1);
console.dir(heading1);
let button = document.getElementById("button");
console.log(button);
console.dir(button);
let tag = document.getElementsByTagName("p");
console.log(tag);
console.dir(tag);
let firstel = document.querySelector("p");
console.log(firstel);
console.dir(firstel);
let all = document.querySelector("p");
console.log(all); 
console.dir(all);
let div = document.querySelector("div");
console.log(div);
console.dir(div);